export default [
	{ flag: "ad.svg", country: "Andorra" },
	{ flag: "ae.svg", country: "Emirati Arabi Uniti" },
	{ flag: "af.svg", country: "Afghanistan" },
	{ flag: "ag.svg", country: "Antigua e Barbuda" },
	{ flag: "ai.svg", country: "Anguilla" },
	{ flag: "al.svg", country: "Albania" },
	{ flag: "am.svg", country: "Armenia" },
	{ flag: "ao.svg", country: "Angola" },
	{ flag: "aq.svg", country: "Antartide" },
	{ flag: "ar.svg", country: "Argentina" },
	{ flag: "as.svg", country: "Samoa Americane" },
	{ flag: "at.svg", country: "Austria" },
	{ flag: "au.svg", country: "Australia" },
	{ flag: "aw.svg", country: "Aruba" },
	{ flag: "ax.svg", country: "Isole Åland" },
	{ flag: "az.svg", country: "Azerbaigian" },
	{ flag: "ba.svg", country: "Bosnia ed Erzegovina" },
	{ flag: "bb.svg", country: "Barbados" },
	{ flag: "bd.svg", country: "Bangladesh" },
	{ flag: "be.svg", country: "Belgio" },
	{ flag: "bf.svg", country: "Burkina Faso" },
	{ flag: "bg.svg", country: "Bulgaria" },
	{ flag: "bh.svg", country: "Bahrain" },
	{ flag: "bi.svg", country: "Burundi" },
	{ flag: "bj.svg", country: "Benin" },
	{ flag: "bl.svg", country: "Saint Barthélemy" },
	{ flag: "bm.svg", country: "Bermuda" },
	{ flag: "bn.svg", country: "Brunei" },
	{ flag: "bo.svg", country: "Bolivia" },
	{ flag: "bq.svg", country: "Bonaire, Sint Eustatius e Saba" },
	{ flag: "br.svg", country: "Brasile" },
	{ flag: "bs.svg", country: "Bahamas" },
	{ flag: "bt.svg", country: "Bhutan" },
	{ flag: "bv.svg", country: "Isola Bouvet" },
	{ flag: "bw.svg", country: "Botswana" },
	{ flag: "by.svg", country: "Bielorussia" },
	{ flag: "bz.svg", country: "Belize" },
	{ flag: "ca.svg", country: "Canada" },
	{ flag: "cc.svg", country: "Isole Cocos (Keeling)" },
	{ flag: "cd.svg", country: "Repubblica Democratica del Congo" },
	{ flag: "cf.svg", country: "Repubblica Centrafricana" },
	{ flag: "cg.svg", country: "Congo" },
	{ flag: "ch.svg", country: "Svizzera" },
	{ flag: "ci.svg", country: "Costa d’Avorio" },
	{ flag: "ck.svg", country: "Isole Cook" },
	{ flag: "cl.svg", country: "Cile" },
	{ flag: "cm.svg", country: "Camerun" },
	{ flag: "cn.svg", country: "Cina" },
	{ flag: "co.svg", country: "Colombia" },
	{ flag: "cr.svg", country: "Costa Rica" },
	{ flag: "cu.svg", country: "Cuba" },
	{ flag: "cv.svg", country: "Capo Verde" },
	{ flag: "cw.svg", country: "Curaçao" },
	{ flag: "cx.svg", country: "Isola Christmas" },
	{ flag: "cy.svg", country: "Cipro" },
	{ flag: "cz.svg", country: "Repubblica Ceca" },
	{ flag: "de.svg", country: "Germania" },
	{ flag: "dj.svg", country: "Gibuti" },
	{ flag: "dk.svg", country: "Danimarca" },
	{ flag: "dm.svg", country: "Dominica" },
	{ flag: "do.svg", country: "Repubblica Dominicana" },
	{ flag: "dz.svg", country: "Algeria" },
	{ flag: "ec.svg", country: "Ecuador" },
	{ flag: "ee.svg", country: "Estonia" },
	{ flag: "eg.svg", country: "Egitto" },
	{ flag: "eh.svg", country: "Sahara Occidentale" },
	{ flag: "er.svg", country: "Eritrea" },
	{ flag: "es.svg", country: "Spagna" },
	{ flag: "et.svg", country: "Etiopia" },
	{ flag: "fi.svg", country: "Finlandia" },
	{ flag: "fj.svg", country: "Figi" },
	{ flag: "fm.svg", country: "Micronesia" },
	{ flag: "fo.svg", country: "Isole Faroe" },
	{ flag: "fr.svg", country: "Francia" },
	{ flag: "ga.svg", country: "Gabon" },
	{ flag: "gb.svg", country: "Regno Unito" },
	{ flag: "gd.svg", country: "Grenada" },
	{ flag: "ge.svg", country: "Georgia" },
	{ flag: "gf.svg", country: "Guiana Francese" },
	{ flag: "gg.svg", country: "Guernsey" },
	{ flag: "gh.svg", country: "Ghana" },
	{ flag: "gi.svg", country: "Gibilterra" },
	{ flag: "gl.svg", country: "Groenlandia" },
	{ flag: "gm.svg", country: "Gambia" },
	{ flag: "gn.svg", country: "Guinea" },
	{ flag: "gp.svg", country: "Guadalupa" },
	{ flag: "gq.svg", country: "Guinea Equatoriale" },
	{ flag: "gr.svg", country: "Grecia" },
	{ flag: "gt.svg", country: "Guatemala" },
	{ flag: "gu.svg", country: "Guam" },
	{ flag: "gw.svg", country: "Guinea-Bissau" },
	{ flag: "gy.svg", country: "Guyana" },
	{ flag: "hk.svg", country: "Hong Kong" },
	{ flag: "hm.svg", country: "Isole Heard e McDonald" },
	{ flag: "hn.svg", country: "Honduras" },
	{ flag: "hr.svg", country: "Croazia" },
	{ flag: "ht.svg", country: "Haiti" },
	{ flag: "hu.svg", country: "Ungheria" },
	{ flag: "id.svg", country: "Indonesia" },
	{ flag: "ie.svg", country: "Irlanda" },
	{ flag: "il.svg", country: "Israele" },
	{ flag: "im.svg", country: "Isola di Man" },
	{ flag: "in.svg", country: "India" },
	{ flag: "io.svg", country: "Territorio Britannico dell’Oceano Indiano" },
	{ flag: "iq.svg", country: "Iraq" },
	{ flag: "ir.svg", country: "Iran" },
	{ flag: "is.svg", country: "Islanda" },
	{ flag: "it.svg", country: "Italia" },
	{ flag: "je.svg", country: "Jersey" },
	{ flag: "jm.svg", country: "Giamaica" },
	{ flag: "jo.svg", country: "Giordania" },
	{ flag: "jp.svg", country: "Giappone" },
	{ flag: "ke.svg", country: "Kenya" },
	{ flag: "kg.svg", country: "Kyrgyzistan" },
	{ flag: "kh.svg", country: "Cambogia" },
	{ flag: "ki.svg", country: "Kiribati" },
	{ flag: "km.svg", country: "Comore" },
	{ flag: "kn.svg", country: "Saint Kitts e Nevis" },
	{ flag: "kp.svg", country: "Corea del Nord" },
	{ flag: "kr.svg", country: "Corea del Sud" },
	{ flag: "kw.svg", country: "Kuwait" },
	{ flag: "ky.svg", country: "Isole Cayman" },
	{ flag: "kz.svg", country: "Kazakistan" },
	{ flag: "la.svg", country: "Laos" },
	{ flag: "lb.svg", country: "Libano" },
	{ flag: "lc.svg", country: "Santa Lucia" },
	{ flag: "li.svg", country: "Liechtenstein" },
	{ flag: "lk.svg", country: "Sri Lanka" },
	{ flag: "lr.svg", country: "Liberia" },
	{ flag: "ls.svg", country: "Lesotho" },
	{ flag: "lt.svg", country: "Lituania" },
	{ flag: "lu.svg", country: "Lussemburgo" },
	{ flag: "lv.svg", country: "Lettonia" },
	{ flag: "ly.svg", country: "Libia" },
	{ flag: "ma.svg", country: "Marocco" },
	{ flag: "mc.svg", country: "Monaco" },
	{ flag: "md.svg", country: "Moldova" },
	{ flag: "me.svg", country: "Montenegro" },
	{ flag: "mf.svg", country: "Saint Martin" },
	{ flag: "mg.svg", country: "Madagascar" },
	{ flag: "mh.svg", country: "Isole Marshall" },
	{ flag: "mk.svg", country: "Macedonia del Nord" },
	{ flag: "ml.svg", country: "Mali" },
	{ flag: "mm.svg", country: "Myanmar" },
	{ flag: "mn.svg", country: "Mongolia" },
	{ flag: "mo.svg", country: "Macao" },
	{ flag: "mp.svg", country: "Isole Marianne Settentrionali" },
	{ flag: "mq.svg", country: "Martinica" },
	{ flag: "mr.svg", country: "Mauritania" },
	{ flag: "ms.svg", country: "Montserrat" },
	{ flag: "mt.svg", country: "Malta" },
	{ flag: "mu.svg", country: "Mauritius" },
	{ flag: "mv.svg", country: "Maldive" },
	{ flag: "mw.svg", country: "Malawi" },
	{ flag: "mx.svg", country: "Messico" },
	{ flag: "my.svg", country: "Malesia" },
	{ flag: "mz.svg", country: "Mozambico" },
	{ flag: "na.svg", country: "Namibia" },
	{ flag: "nc.svg", country: "Nuova Caledonia" },
	{ flag: "ne.svg", country: "Niger" },
	{ flag: "nf.svg", country: "Isola Norfolk" },
	{ flag: "ng.svg", country: "Nigeria" },
	{ flag: "ni.svg", country: "Nicaragua" },
	{ flag: "nl.svg", country: "Paesi Bassi" },
	{ flag: "no.svg", country: "Norvegia" },
	{ flag: "np.svg", country: "Nepal" },
	{ flag: "nr.svg", country: "Nauru" },
	{ flag: "nu.svg", country: "Niue" },
	{ flag: "nz.svg", country: "Nuova Zelanda" },
	{ flag: "om.svg", country: "Oman" },
	{ flag: "pa.svg", country: "Panama" },
	{ flag: "pe.svg", country: "Perù" },
	{ flag: "pf.svg", country: "Polinesia Francese" },
	{ flag: "pg.svg", country: "Papua Nuova Guinea" },
	{ flag: "ph.svg", country: "Filippine" },
	{ flag: "pk.svg", country: "Pakistan" },
	{ flag: "pl.svg", country: "Polonia" },
	{ flag: "pm.svg", country: "Saint Pierre e Miquelon" },
	{ flag: "pn.svg", country: "Isole Pitcairn" },
	{ flag: "pr.svg", country: "Porto Rico" },
	{ flag: "pt.svg", country: "Portogallo" },
	{ flag: "pw.svg", country: "Palau" },
	{ flag: "py.svg", country: "Paraguay" },
	{ flag: "qa.svg", country: "Qatar" },
	{ flag: "re.svg", country: "Riunione" },
	{ flag: "ro.svg", country: "Romania" },
	{ flag: "rs.svg", country: "Serbia" },
	{ flag: "ru.svg", country: "Russia" },
	{ flag: "rw.svg", country: "Ruanda" },
	{ flag: "sa.svg", country: "Arabia Saudita" },
	{ flag: "sb.svg", country: "Isole Solomon" },
	{ flag: "sc.svg", country: "Seychelles" },
	{ flag: "sd.svg", country: "Sudan" },
	{ flag: "se.svg", country: "Svezia" },
	{ flag: "sg.svg", country: "Singapore" },
	{ flag: "sh.svg", country: "Sant’Elena" },
	{ flag: "si.svg", country: "Slovenia" },
	{ flag: "sj.svg", country: "Svalbard e Jan Mayen" },
	{ flag: "sk.svg", country: "Slovacchia" },
	{ flag: "sl.svg", country: "Sierra Leone" },
	{ flag: "sm.svg", country: "San Marino" },
	{ flag: "sn.svg", country: "Senegal" },
	{ flag: "so.svg", country: "Somalia" },
	{ flag: "sr.svg", country: "Suriname" },
	{ flag: "ss.svg", country: "Sudan del Sud" },
	{ flag: "st.svg", country: "Santo Stefano" },
	{ flag: "sv.svg", country: "El Salvador" },
	{ flag: "sx.svg", country: "Sint Maarten" },
	{ flag: "sy.svg", country: "Siria" },
	{ flag: "sz.svg", country: "Eswatini" },
	{ flag: "tc.svg", country: "Isole Turks e Caicos" },
	{ flag: "td.svg", country: "Ciad" },
	{ flag: "tf.svg", country: "Territori del Sud della Francia" },
	{ flag: "tg.svg", country: "Togo" },
	{ flag: "th.svg", country: "Thailandia" },
	{ flag: "tj.svg", country: "Tagikistan" },
	{ flag: "tk.svg", country: "Tokelau" },
	{ flag: "tl.svg", country: "Timor Est" },
	{ flag: "tm.svg", country: "Turkmenistan" },
	{ flag: "tn.svg", country: "Tunisia" },
	{ flag: "to.svg", country: "Tonga" },
	{ flag: "tr.svg", country: "Turchia" },
	{ flag: "tt.svg", country: "Trinidad e Tobago" },
	{ flag: "tv.svg", country: "Tuvalu" },
	{ flag: "tz.svg", country: "Tanzania" },
	{ flag: "ua.svg", country: "Ucraina" },
	{ flag: "ug.svg", country: "Uganda" },
	{ flag: "uk.svg", country: "Regno Unito" },
	{ flag: "us.svg", country: "Stati Uniti d’America" },
	{ flag: "uy.svg", country: "Uruguay" },
	{ flag: "uz.svg", country: "Uzbekistan" },
	{ flag: "va.svg", country: "Città del Vaticano" },
	{ flag: "vc.svg", country: "Saint Vincent e Grenadine" },
	{ flag: "ve.svg", country: "Venezuela" },
	{ flag: "vg.svg", country: "Isole Vergini Britanniche" },
	{ flag: "vi.svg", country: "Isole Vergini Americane" },
	{ flag: "vn.svg", country: "Vietnam" },
	{ flag: "vu.svg", country: "Vanuatu" },
	{ flag: "wf.svg", country: "Wallis e Futuna" },
	{ flag: "ws.svg", country: "Samoa" },
	{ flag: "ye.svg", country: "Yemen" },
	{ flag: "yt.svg", country: "Mayotte" },
	{ flag: "za.svg", country: "Sudafrica" },
	{ flag: "zm.svg", country: "Zambia" },
	{ flag: "zw.svg", country: "Zimbabwe" },
];
